obj-$(CONFIG_CAMERA_FPGA_DPHY) += fimc-is-fpga-dphy.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star/sensor
