obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-interface-ischain.o \
		fimc-is-interface-library.o \
		fimc-is-interface-vra.o \
		fimc-is-interface-ddk.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2_star/vendor
