obj-$(CONFIG_CAMERA_APERTURE_AK7372_OBJ) += fimc-is-aperture-ak7372.o

ccflags-y := -Idrivers/media/platform/exynos/fimc-is2_star
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2_star/include
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2_star/vendor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2_star/hardware/api
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2_star/sensor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2_star/sensor/module_framework
